// PROGRAMMING ERROR MASTER CATALOG
// Rebuild: katalog diperluas dari error fundamental sampai failure mode level expert/architect.
// Prinsip: jangan hanya hafal nama error; pahami gejala -> penyebab -> mekanisme -> diagnosis -> pencegahan.

export interface CatalogRow {
  id: string;
  gejala: string;
  penyebab: string;
  konsep: string;
}

export interface CatalogTier {
  id: string;
  title: string;
  subtitle: string;
  rows: CatalogRow[];
}

export const CATALOG_TIERS: CatalogTier[] = [
  {
    id: 'tier1',
    title: 'TIER 1 — Syntax, Types & Basic Runtime',
    subtitle: 'Junior',
    rows: [
      { id: 't1-1', gejala: 'Unexpected token / SyntaxError', penyebab: 'Parser menemukan sintaks yang tidak valid', konsep: 'Syntax Grammar, Parser, AST' },
      { id: 't1-2', gejala: 'Missing ) / } / ]', penyebab: 'Delimiter pembuka dan penutup tidak seimbang', konsep: 'Bracket Matching, Syntax Highlighting' },
      { id: 't1-3', gejala: 'Variable is not defined / ReferenceError', penyebab: 'Identifier dipakai sebelum didefinisikan atau salah scope', konsep: 'Scope, Hoisting, Name Resolution' },
      { id: 't1-4', gejala: 'undefined / null / None access', penyebab: 'Nilai kosong diperlakukan sebagai object', konsep: 'Null Safety, Optional Chaining, Guard Clause' },
      { id: 't1-5', gejala: 'is not a function / not callable', penyebab: 'Nilai yang dipanggil bukan function', konsep: 'Type Checking, Runtime Type Inspection' },
      { id: 't1-6', gejala: 'Cannot read property of undefined', penyebab: 'Object parent ternyata kosong', konsep: 'Defensive Programming, Nullish Handling' },
      { id: 't1-7', gejala: 'Type mismatch', penyebab: 'Operasi menerima tipe yang tidak sesuai', konsep: 'Static Typing, Runtime Validation' },
      { id: 't1-8', gejala: 'Implicit type coercion', penyebab: 'Bahasa mengubah tipe secara otomatis', konsep: 'Coercion Rules, Strict Equality' },
      { id: 't1-9', gejala: 'NaN menyebar ke hasil', penyebab: 'Operasi numerik menghasilkan nilai bukan angka', konsep: 'Number Validation, isFinite' },
      { id: 't1-10', gejala: 'Infinity / overflow', penyebab: 'Nilai numerik melewati batas representasi', konsep: 'Numeric Limits, Overflow Handling' },
      { id: 't1-11', gejala: 'Floating-point precision', penyebab: '0.1 + 0.2 menghasilkan representasi tak persis', konsep: 'IEEE-754, Decimal Arithmetic' },
      { id: 't1-12', gejala: 'Integer overflow / underflow', penyebab: 'Nilai integer melewati kapasitas tipe', konsep: 'Checked Arithmetic, BigInt' },
      { id: 't1-13', gejala: 'Off-by-one', penyebab: 'Loop/index mengambil satu elemen terlalu banyak/kurang', konsep: 'Boundary Conditions' },
      { id: 't1-14', gejala: 'Infinite loop', penyebab: 'Kondisi terminasi tidak pernah tercapai', konsep: 'Loop Invariant, Progress Measure' },
      { id: 't1-15', gejala: 'Infinite recursion / stack overflow', penyebab: 'Recursive call tidak mencapai base case', konsep: 'Base Case, Stack Frames' },
      { id: 't1-16', gejala: 'Mutable default / shared state', penyebab: 'State default dipakai bersama tanpa sengaja', konsep: 'Immutability, Instance Isolation' },
      { id: 't1-17', gejala: 'Variable shadowing', penyebab: 'Identifier lokal menutupi identifier luar', konsep: 'Lexical Scope, Naming' },
      { id: 't1-18', gejala: 'Uninitialized value', penyebab: 'Program membaca nilai sebelum valid diinisialisasi', konsep: 'Initialization Invariants' },
    ],
  },
  {
    id: 'tier2',
    title: 'TIER 2 — Logic, State & Data',
    subtitle: 'Junior–Mid',
    rows: [
      { id: 't2-1', gejala: 'Wrong boolean condition', penyebab: 'AND/OR/NOT menghasilkan cabang yang salah', konsep: 'Boolean Algebra, Truth Tables' },
      { id: 't2-2', gejala: 'Operator precedence bug', penyebab: 'Ekspresi dievaluasi dalam urutan yang tidak dimaksud', konsep: 'Precedence, Parentheses' },
      { id: 't2-3', gejala: 'Assignment vs comparison', penyebab: 'Nilai diubah ketika seharusnya dibandingkan', konsep: 'Operator Semantics' },
      { id: 't2-4', gejala: 'Boundary condition bug', penyebab: 'Kasus tepat di batas gagal', konsep: 'Boundary Value Analysis' },
      { id: 't2-5', gejala: 'Empty collection bug', penyebab: 'Kode mengasumsikan array/list selalu berisi data', konsep: 'Empty-State Handling' },
      { id: 't2-6', gejala: 'Duplicate data', penyebab: 'Operasi insert/retry menghasilkan record ganda', konsep: 'Uniqueness, Idempotency' },
      { id: 't2-7', gejala: 'Stale state', penyebab: 'Kode membaca state lama setelah state berubah', konsep: 'State Synchronization' },
      { id: 't2-8', gejala: 'Lost update', penyebab: 'Perubahan satu proses menimpa perubahan proses lain', konsep: 'Concurrency Control' },
      { id: 't2-9', gejala: 'Wrong sorting', penyebab: 'String/numeric/date disortir dengan aturan salah', konsep: 'Comparator Design' },
      { id: 't2-10', gejala: 'Locale bug', penyebab: 'Format angka/tanggal berbeda antar locale', konsep: 'Locale-aware Formatting' },
      { id: 't2-11', gejala: 'Timezone / DST bug', penyebab: 'Waktu bergeser karena timezone atau daylight saving', konsep: 'UTC, IANA Time Zone' },
      { id: 't2-12', gejala: 'Encoding/mojibake', penyebab: 'Karakter rusak karena encoding berbeda', konsep: 'Unicode, UTF-8' },
      { id: 't2-13', gejala: 'Precision/rounding error', penyebab: 'Pembulatan menghasilkan keputusan finansial salah', konsep: 'Decimal Arithmetic, Rounding Policy' },
      { id: 't2-14', gejala: 'Unit conversion bug', penyebab: 'Meter, kilometer, ms, s, byte, MiB tercampur', konsep: 'Dimensional Analysis' },
      { id: 't2-15', gejala: 'Schema drift', penyebab: 'Bentuk data berubah tanpa consumer diperbarui', konsep: 'Schema Contracts' },
      { id: 't2-16', gejala: 'Partial data', penyebab: 'Objek hanya berisi sebagian field yang diasumsikan tersedia', konsep: 'Data Completeness' },
      { id: 't2-17', gejala: 'Sentinel value collision', penyebab: 'Nilai khusus seperti -1 ternyata merupakan data valid', konsep: 'Explicit Result Types' },
      { id: 't2-18', gejala: 'Falsy/truthy bug', penyebab: 'Nilai valid seperti 0/false/\'\' dianggap tidak ada', konsep: 'Nullish vs Boolean Semantics' },
    ],
  },
  {
    id: 'tier3',
    title: 'TIER 3 — Async, Promise & Event Loop',
    subtitle: 'Mid',
    rows: [
      { id: 't3-1', gejala: 'Unhandled promise rejection', penyebab: 'Promise gagal tetapi tidak ditangani', konsep: 'Promise Error Propagation' },
      { id: 't3-2', gejala: 'Forgotten await', penyebab: 'Program meneruskan Promise sebagai data', konsep: 'Async/Await Semantics' },
      { id: 't3-3', gejala: 'Await in wrong place', penyebab: 'Operasi async berjalan serial padahal dapat paralel', konsep: 'Concurrency with Promise.all' },
      { id: 't3-4', gejala: 'Race condition', penyebab: 'Hasil bergantung pada urutan eksekusi', konsep: 'Synchronization, Atomicity' },
      { id: 't3-5', gejala: 'Out-of-order response', penyebab: 'Response request lama tiba setelah request baru', konsep: 'Cancellation, Sequence Token' },
      { id: 't3-6', gejala: 'Double callback', penyebab: 'Callback dipanggil lebih dari sekali', konsep: 'Once Semantics, State Machine' },
      { id: 't3-7', gejala: 'Callback hell', penyebab: 'Nested async flow sulit dikontrol', konsep: 'Composition, Async Abstraction' },
      { id: 't3-8', gejala: 'Event listener leak', penyebab: 'Listener terus bertambah dan tidak dibersihkan', konsep: 'Lifecycle Cleanup' },
      { id: 't3-9', gejala: 'Event handler reentrancy', penyebab: 'Handler memicu dirinya sendiri secara tidak langsung', konsep: 'Reentrancy Guard' },
      { id: 't3-10', gejala: 'Deadlock', penyebab: 'Dua atau lebih pekerjaan saling menunggu resource', konsep: 'Lock Ordering' },
      { id: 't3-11', gejala: 'Livelock', penyebab: 'Proses aktif tetapi tidak membuat progress', konsep: 'Progress Guarantees' },
      { id: 't3-12', gejala: 'Starvation', penyebab: 'Task tertentu terus tidak mendapat resource', konsep: 'Fair Scheduling' },
      { id: 't3-13', gejala: 'Thundering herd', penyebab: 'Banyak worker/request aktif bersamaan setelah satu event', konsep: 'Jitter, Backoff' },
      { id: 't3-14', gejala: 'Timer drift', penyebab: 'setTimeout/interval tidak presisi terhadap waktu nyata', konsep: 'Event Loop Scheduling' },
      { id: 't3-15', gejala: 'Backpressure failure', penyebab: 'Producer menghasilkan data lebih cepat dari consumer', konsep: 'Flow Control, Queue Backpressure' },
      { id: 't3-16', gejala: 'Cancellation bug', penyebab: 'Task dibatalkan tetapi side effect tetap berjalan', konsep: 'Cancellation Propagation' },
    ],
  },
  {
    id: 'tier4',
    title: 'TIER 4 — Functions, Modules & Architecture',
    subtitle: 'Mid',
    rows: [
      { id: 't4-1', gejala: 'Circular dependency', penyebab: 'Module A membutuhkan B dan B membutuhkan A', konsep: 'Dependency Graph' },
      { id: 't4-2', gejala: 'Import/export mismatch', penyebab: 'Nama export dan import tidak cocok', konsep: 'Module Resolution' },
      { id: 't4-3', gejala: 'Initialization order bug', penyebab: 'Module memakai dependency sebelum siap', konsep: 'Module Lifecycle' },
      { id: 't4-4', gejala: 'Global state contamination', penyebab: 'State global berubah dari tempat yang tidak terduga', konsep: 'State Isolation' },
      { id: 't4-5', gejala: 'Tight coupling', penyebab: 'Perubahan implementasi merusak banyak modul', konsep: 'Abstraction, Dependency Inversion' },
      { id: 't4-6', gejala: 'God object/function', penyebab: 'Satu komponen memegang terlalu banyak tanggung jawab', konsep: 'SRP, Modular Design' },
      { id: 't4-7', gejala: 'Shotgun surgery', penyebab: 'Satu perubahan memerlukan edit di banyak tempat', konsep: 'Cohesion, Encapsulation' },
      { id: 't4-8', gejala: 'Leaky abstraction', penyebab: 'Detail internal bocor ke caller', konsep: 'Information Hiding' },
      { id: 't4-9', gejala: 'Wrong abstraction', penyebab: 'Abstraksi membuat sistem lebih kompleks', konsep: 'Design by Domain Boundaries' },
      { id: 't4-10', gejala: 'Temporal coupling', penyebab: 'API harus dipanggil dalam urutan tertentu tanpa kontrak jelas', konsep: 'State Machine' },
      { id: 't4-11', gejala: 'Hidden side effect', penyebab: 'Function terlihat pure tetapi mengubah state eksternal', konsep: 'Functional Programming' },
      { id: 't4-12', gejala: 'Dependency injection failure', penyebab: 'Dependency dibuat internal sehingga sulit diganti/test', konsep: 'Dependency Injection' },
      { id: 't4-13', gejala: 'Configuration drift', penyebab: 'Environment memiliki konfigurasi berbeda tanpa kontrol', konsep: 'Configuration Management' },
      { id: 't4-14', gejala: 'API contract break', penyebab: 'Provider mengubah response/request tanpa kompatibilitas', konsep: 'Versioning, Contract Testing' },
    ],
  },
  {
    id: 'tier5',
    title: 'TIER 5 — HTTP, API & Distributed Requests',
    subtitle: 'Mid',
    rows: [
      { id: 't5-1', gejala: '400 Bad Request', penyebab: 'Request malformed atau gagal validasi', konsep: 'Input Validation' },
      { id: 't5-2', gejala: '401 Unauthorized', penyebab: 'Identity tidak valid/tidak ada', konsep: 'Authentication' },
      { id: 't5-3', gejala: '403 Forbidden', penyebab: 'Identity ada tetapi tidak berhak', konsep: 'Authorization' },
      { id: 't5-4', gejala: '404 Not Found', penyebab: 'Resource/route tidak ditemukan', konsep: 'Routing, Resource Semantics' },
      { id: 't5-5', gejala: '405 Method Not Allowed', penyebab: 'HTTP method tidak didukung endpoint', konsep: 'HTTP Semantics' },
      { id: 't5-6', gejala: '409 Conflict', penyebab: 'Request bertentangan dengan current state', konsep: 'Conflict Semantics' },
      { id: 't5-7', gejala: '415 Unsupported Media Type', penyebab: 'Content-Type tidak sesuai', konsep: 'Content Negotiation' },
      { id: 't5-8', gejala: '422 Unprocessable Content', penyebab: 'Sintaks valid tetapi semantic validation gagal', konsep: 'Schema Validation' },
      { id: 't5-9', gejala: '429 Too Many Requests', penyebab: 'Client melewati rate limit', konsep: 'Rate Limiting' },
      { id: 't5-10', gejala: '500 Internal Server Error', penyebab: 'Unhandled server failure', konsep: 'Centralized Error Handling' },
      { id: 't5-11', gejala: '502 Bad Gateway', penyebab: 'Gateway menerima response invalid dari upstream', konsep: 'Reverse Proxy, Upstream Health' },
      { id: 't5-12', gejala: '503 Service Unavailable', penyebab: 'Service sementara tidak siap', konsep: 'Health Checks, Load Shedding' },
      { id: 't5-13', gejala: '504 Gateway Timeout', penyebab: 'Upstream tidak merespons tepat waktu', konsep: 'Timeout Budget' },
      { id: 't5-14', gejala: 'Connection reset', penyebab: 'Socket diputus oleh peer/network', konsep: 'Retry Policy, Network Diagnostics' },
      { id: 't5-15', gejala: 'DNS failure', penyebab: 'Hostname tidak dapat di-resolve', konsep: 'DNS, Resolver Debugging' },
      { id: 't5-16', gejala: 'TLS/certificate error', penyebab: 'Handshake gagal atau certificate tidak valid', konsep: 'PKI, TLS' },
      { id: 't5-17', gejala: 'CORS failure', penyebab: 'Browser memblokir cross-origin request', konsep: 'Origin Policy, CORS Headers' },
      { id: 't5-18', gejala: 'Payload too large', penyebab: 'Request melewati limit body', konsep: 'Request Limits, Streaming' },
      { id: 't5-19', gejala: 'Content negotiation bug', penyebab: 'Client dan server tidak sepakat format data', konsep: 'Accept/Content-Type' },
      { id: 't5-20', gejala: 'Retry storm', penyebab: 'Retry massal memperparah outage', konsep: 'Exponential Backoff, Jitter' },
      { id: 't5-21', gejala: 'Idempotency failure', penyebab: 'Retry menghasilkan side effect ganda', konsep: 'Idempotency Key' },
    ],
  },
  {
    id: 'tier6',
    title: 'TIER 6 — Database & SQL',
    subtitle: 'Mid–Senior',
    rows: [
      { id: 't6-1', gejala: 'SQL syntax error', penyebab: 'Query tidak valid menurut grammar SQL', konsep: 'SQL Parser' },
      { id: 't6-2', gejala: 'Constraint violation', penyebab: 'INSERT/UPDATE melanggar constraint', konsep: 'PK, FK, UNIQUE, CHECK' },
      { id: 't6-3', gejala: 'Foreign key violation', penyebab: 'Referensi parent tidak ada atau parent dihapus', konsep: 'Referential Integrity' },
      { id: 't6-4', gejala: 'Unique constraint violation', penyebab: 'Nilai unik masuk dua kali', konsep: 'Unique Index, Upsert' },
      { id: 't6-5', gejala: 'Null constraint violation', penyebab: 'Kolom wajib menerima NULL', konsep: 'NOT NULL, Defaults' },
      { id: 't6-6', gejala: 'Transaction partial failure', penyebab: 'Sebagian operasi berhasil sebelum error', konsep: 'BEGIN/COMMIT/ROLLBACK' },
      { id: 't6-7', gejala: 'Lost update', penyebab: 'Update transaksi saling menimpa', konsep: 'Optimistic/Pessimistic Locking' },
      { id: 't6-8', gejala: 'Dirty read', penyebab: 'Membaca data yang belum committed', konsep: 'Isolation Level' },
      { id: 't6-9', gejala: 'Non-repeatable read', penyebab: 'Row yang sama berubah dalam satu transaksi', konsep: 'Isolation Level' },
      { id: 't6-10', gejala: 'Phantom read', penyebab: 'Query kedua melihat row baru/berubah', konsep: 'Isolation Level' },
      { id: 't6-11', gejala: 'Deadlock', penyebab: 'Transaksi saling menunggu lock', konsep: 'Lock Ordering, Deadlock Detection' },
      { id: 't6-12', gejala: 'Long-running transaction', penyebab: 'Transaction menahan resource terlalu lama', konsep: 'Transaction Scope' },
      { id: 't6-13', gejala: 'Connection pool exhaustion', penyebab: 'Semua DB connection sedang terpakai', konsep: 'Pool Sizing, Connection Lifecycle' },
      { id: 't6-14', gejala: 'N+1 query', penyebab: 'Satu query diikuti query per item', konsep: 'Join, Batching, Eager Loading' },
      { id: 't6-15', gejala: 'Missing index', penyebab: 'Query melakukan scan besar', konsep: 'Indexing, EXPLAIN' },
      { id: 't6-16', gejala: 'Wrong index', penyebab: 'Index ada tetapi tidak dipilih/efektif', konsep: 'Query Planner' },
      { id: 't6-17', gejala: 'Slow query', penyebab: 'Query melebihi latency budget', konsep: 'Execution Plan, Statistics' },
      { id: 't6-18', gejala: 'Lock contention', penyebab: 'Banyak transaksi berebut lock yang sama', konsep: 'Contention Analysis' },
      { id: 't6-19', gejala: 'Replication lag', penyebab: 'Replica tertinggal dari primary', konsep: 'Replication Monitoring' },
      { id: 't6-20', gejala: 'Read-after-write inconsistency', penyebab: 'Write berhasil tetapi read replica belum melihatnya', konsep: 'Consistency Model' },
      { id: 't6-21', gejala: 'Migration failure', penyebab: 'Schema migration gagal di tengah deployment', konsep: 'Transactional Migration, Rollback' },
      { id: 't6-22', gejala: 'Schema migration incompatibility', penyebab: 'App lama/baru tidak kompatibel dengan schema', konsep: 'Expand/Contract Migration' },
      { id: 't6-23', gejala: 'Backup restore failure', penyebab: 'Backup tersedia tetapi tidak dapat dipulihkan', konsep: 'Restore Testing' },
    ],
  },
  {
    id: 'tier7',
    title: 'TIER 7 — Security & Adversarial Failure',
    subtitle: 'Mid–Senior',
    rows: [
      { id: 't7-1', gejala: 'SQL Injection', penyebab: 'Input memengaruhi struktur query', konsep: 'Parameterized Queries' },
      { id: 't7-2', gejala: 'XSS', penyebab: 'Input menjadi executable script di browser', konsep: 'Output Encoding, CSP' },
      { id: 't7-3', gejala: 'CSRF', penyebab: 'Request berotorisasi dipicu dari origin berbahaya', konsep: 'CSRF Token, SameSite' },
      { id: 't7-4', gejala: 'Broken access control', penyebab: 'User dapat mengakses resource milik user lain', konsep: 'Authorization, Object-level Access Control' },
      { id: 't7-5', gejala: 'IDOR/BOLA', penyebab: 'ID resource dapat diganti dan server tetap memberi akses', konsep: 'Resource Authorization' },
      { id: 't7-6', gejala: 'Session fixation', penyebab: 'Attacker memaksa session identifier korban', konsep: 'Session Rotation' },
      { id: 't7-7', gejala: 'Session hijacking', penyebab: 'Session/token dicuri dan digunakan pihak lain', konsep: 'Secure Cookies, Token Protection' },
      { id: 't7-8', gejala: 'JWT misuse', penyebab: 'Token terlalu lama/claim dipercaya tanpa verifikasi', konsep: 'JWT Validation, Expiry' },
      { id: 't7-9', gejala: 'Password storage failure', penyebab: 'Password disimpan plain text atau hash lemah', konsep: 'Argon2id/bcrypt, Salt' },
      { id: 't7-10', gejala: 'Credential leakage', penyebab: 'Secret masuk repository/log/client bundle', konsep: 'Secrets Management' },
      { id: 't7-11', gejala: 'SSRF', penyebab: 'Server dipaksa mengakses resource internal', konsep: 'URL Allowlist, Network Egress Control' },
      { id: 't7-12', gejala: 'Path traversal', penyebab: 'Input path mengakses file di luar direktori', konsep: 'Path Canonicalization' },
      { id: 't7-13', gejala: 'Command injection', penyebab: 'Input masuk shell command', konsep: 'Avoid Shell, Argument APIs' },
      { id: 't7-14', gejala: 'Deserialization vulnerability', penyebab: 'Data tak tepercaya menjadi object berbahaya', konsep: 'Safe Serialization' },
      { id: 't7-15', gejala: 'Prototype pollution', penyebab: 'Object prototype dimodifikasi melalui input', konsep: 'Input Validation, Object Hardening' },
      { id: 't7-16', gejala: 'Open redirect', penyebab: 'URL redirect dapat dikontrol attacker', konsep: 'Allowlisted Redirect Targets' },
      { id: 't7-17', gejala: 'Clickjacking', penyebab: 'UI ditumpuk/di-frame untuk menipu user', konsep: 'CSP frame-ancestors, X-Frame-Options' },
      { id: 't7-18', gejala: 'CORS misconfiguration', penyebab: 'Origin terlalu permisif atau credentials salah', konsep: 'Strict Origin Policy' },
      { id: 't7-19', gejala: 'Rate-limit bypass', penyebab: 'Attacker menghindari limit dengan banyak identitas/IP', konsep: 'Distributed Rate Limiting' },
      { id: 't7-20', gejala: 'Timing side channel', penyebab: 'Waktu respons membocorkan informasi rahasia', konsep: 'Constant-time Comparison' },
    ],
  },
  {
    id: 'tier8',
    title: 'TIER 8 — Memory, Runtime & Low-Level',
    subtitle: 'Senior',
    rows: [
      { id: 't8-1', gejala: 'Memory leak', penyebab: 'Memory tidak lagi diperlukan tetapi tetap direferensikan', konsep: 'Heap Profiling, Ownership' },
      { id: 't8-2', gejala: 'Use-after-free', penyebab: 'Memory digunakan setelah dibebaskan', konsep: 'Memory Safety' },
      { id: 't8-3', gejala: 'Double free', penyebab: 'Memory dibebaskan dua kali', konsep: 'Ownership Discipline' },
      { id: 't8-4', gejala: 'Buffer overflow', penyebab: 'Penulisan melewati batas buffer', konsep: 'Bounds Checking' },
      { id: 't8-5', gejala: 'Buffer underflow', penyebab: 'Akses sebelum awal buffer', konsep: 'Bounds Checking' },
      { id: 't8-6', gejala: 'Out-of-bounds access', penyebab: 'Index/pointer melewati batas', konsep: 'Memory Safety' },
      { id: 't8-7', gejala: 'Dangling pointer', penyebab: 'Pointer menunjuk ke object yang sudah tidak valid', konsep: 'Lifetime Analysis' },
      { id: 't8-8', gejala: 'Null pointer dereference', penyebab: 'Pointer null diakses', konsep: 'Pointer Safety' },
      { id: 't8-9', gejala: 'Data race', penyebab: 'Thread mengakses memory bersama tanpa sinkronisasi', konsep: 'Mutex, Atomic Operations' },
      { id: 't8-10', gejala: 'Undefined behavior', penyebab: 'Program melakukan operasi yang tidak didefinisikan bahasa', konsep: 'Language Semantics, Sanitizers' },
      { id: 't8-11', gejala: 'Use of uninitialized memory', penyebab: 'Memory dibaca sebelum diinisialisasi', konsep: 'Memory Initialization' },
      { id: 't8-12', gejala: 'Stack overflow', penyebab: 'Stack frame melebihi kapasitas', konsep: 'Recursion Depth, Stack Usage' },
      { id: 't8-13', gejala: 'Heap corruption', penyebab: 'Metadata/struktur heap rusak akibat memory misuse', konsep: 'Heap Sanitizer' },
      { id: 't8-14', gejala: 'Alignment fault', penyebab: 'Akses memory tidak memenuhi alignment platform', konsep: 'Data Alignment' },
      { id: 't8-15', gejala: 'Integer signedness bug', penyebab: 'Signed/unsigned conversion menghasilkan nilai tak terduga', konsep: 'Integer Semantics' },
      { id: 't8-16', gejala: 'ABI mismatch', penyebab: 'Binary/object tidak kompatibel pada calling convention/layout', konsep: 'ABI, Toolchain Compatibility' },
      { id: 't8-17', gejala: 'Data race on volatile state', penyebab: 'Nilai berubah tanpa synchronization yang benar', konsep: 'Atomics, Memory Ordering' },
    ],
  },
  {
    id: 'tier9',
    title: 'TIER 9 — Concurrency, Parallelism & Distributed Systems',
    subtitle: 'Senior',
    rows: [
      { id: 't9-1', gejala: 'Race condition', penyebab: 'Hasil bergantung pada timing antar worker', konsep: 'Synchronization' },
      { id: 't9-2', gejala: 'Deadlock', penyebab: 'Worker saling menunggu resource', konsep: 'Lock Graph' },
      { id: 't9-3', gejala: 'Livelock', penyebab: 'Worker terus bereaksi tetapi tidak maju', konsep: 'Progress Analysis' },
      { id: 't9-4', gejala: 'Starvation', penyebab: 'Worker tertentu tidak pernah mendapat resource', konsep: 'Fairness' },
      { id: 't9-5', gejala: 'Split brain', penyebab: 'Node menganggap dirinya masing-masing sebagai leader', konsep: 'Consensus, Fencing' },
      { id: 't9-6', gejala: 'Leader election failure', penyebab: 'Tidak ada leader yang stabil', konsep: 'Consensus Protocol' },
      { id: 't9-7', gejala: 'Network partition', penyebab: 'Node tidak dapat berkomunikasi sebagian', konsep: 'CAP, Failure Detection' },
      { id: 't9-8', gejala: 'Clock skew', penyebab: 'Jam antar mesin berbeda', konsep: 'Logical Clocks, NTP' },
      { id: 't9-9', gejala: 'Duplicate message', penyebab: 'Message delivery lebih dari sekali', konsep: 'Idempotent Consumer' },
      { id: 't9-10', gejala: 'Lost message', penyebab: 'Message hilang sebelum diproses', konsep: 'Durable Queue, Ack' },
      { id: 't9-11', gejala: 'Out-of-order message', penyebab: 'Event tiba tidak sesuai urutan', konsep: 'Sequence Number, Event Ordering' },
      { id: 't9-12', gejala: 'Poison message', penyebab: 'Satu message terus gagal diproses', konsep: 'Dead-letter Queue' },
      { id: 't9-13', gejala: 'Retry amplification', penyebab: 'Retry client + service + queue memperbanyak traffic', konsep: 'Retry Budget' },
      { id: 't9-14', gejala: 'Cascading failure', penyebab: 'Satu dependency failure menjalar ke seluruh sistem', konsep: 'Bulkhead, Circuit Breaker' },
      { id: 't9-15', gejala: 'Partial failure', penyebab: 'Sebagian sistem gagal sementara bagian lain hidup', konsep: 'Failure-aware Design' },
      { id: 't9-16', gejala: 'Thundering herd', penyebab: 'Banyak client retry/refresh bersamaan', konsep: 'Jitter, Singleflight' },
      { id: 't9-17', gejala: 'Eventual consistency surprise', penyebab: 'Read belum mencerminkan write terbaru', konsep: 'Consistency Contracts' },
      { id: 't9-18', gejala: 'Distributed transaction failure', penyebab: 'Commit tidak atomik lintas service', konsep: 'Saga, Outbox' },
      { id: 't9-19', gejala: 'Duplicate side effect', penyebab: 'At-least-once delivery menjalankan efek dua kali', konsep: 'Idempotency' },
      { id: 't9-20', gejala: 'Exactly-once illusion', penyebab: 'Sistem menganggap delivery benar-benar sekali padahal tidak', konsep: 'Delivery Semantics' },
    ],
  },
  {
    id: 'tier10',
    title: 'TIER 10 — Cache, Queue & Messaging',
    subtitle: 'Senior',
    rows: [
      { id: 't10-1', gejala: 'Cache stale data', penyebab: 'Cache menyimpan nilai lama', konsep: 'Invalidation Strategy' },
      { id: 't10-2', gejala: 'Cache stampede', penyebab: 'Banyak request menghantam DB saat cache expired', konsep: 'Singleflight, TTL Jitter' },
      { id: 't10-3', gejala: 'Cache penetration', penyebab: 'Request untuk key invalid terus melewati cache', konsep: 'Negative Caching' },
      { id: 't10-4', gejala: 'Cache avalanche', penyebab: 'Banyak key expired bersamaan', konsep: 'Jittered TTL' },
      { id: 't10-5', gejala: 'Cache inconsistency', penyebab: 'DB dan cache berbeda state', konsep: 'Write-through/Invalidate' },
      { id: 't10-6', gejala: 'Hot key', penyebab: 'Satu key menerima traffic ekstrem', konsep: 'Key Sharding, Replication' },
      { id: 't10-7', gejala: 'Queue backlog', penyebab: 'Producer lebih cepat dari consumer', konsep: 'Consumer Scaling, Backpressure' },
      { id: 't10-8', gejala: 'Queue starvation', penyebab: 'Pesan tertentu tidak pernah diproses', konsep: 'Fair Scheduling' },
      { id: 't10-9', gejala: 'Poison message', penyebab: 'Pesan selalu gagal dan mengulang', konsep: 'Dead-letter Queue' },
      { id: 't10-10', gejala: 'Ack loss', penyebab: 'Consumer memproses tetapi ack hilang sehingga message dikirim lagi', konsep: 'Idempotent Consumer' },
      { id: 't10-11', gejala: 'Visibility timeout race', penyebab: 'Message kembali terlihat sebelum processing selesai', konsep: 'Lease Extension' },
      { id: 't10-12', gejala: 'Consumer group rebalance storm', penyebab: 'Consumer sering join/leave sehingga processing terganggu', konsep: 'Stable Membership' },
      { id: 't10-13', gejala: 'Ordering violation', penyebab: 'Message order berubah', konsep: 'Partitioning, Sequence Numbers' },
      { id: 't10-14', gejala: 'Duplicate delivery', penyebab: 'Broker mengirim ulang message', konsep: 'Idempotency' },
      { id: 't10-15', gejala: 'Outbox inconsistency', penyebab: 'DB commit berhasil tetapi event gagal dipublish', konsep: 'Transactional Outbox' },
      { id: 't10-16', gejala: 'Inbox duplication', penyebab: 'Event sama diproses berkali-kali', konsep: 'Inbox/Deduplication' },
    ],
  },
  {
    id: 'tier11',
    title: 'TIER 11 — Frontend, Browser & UI',
    subtitle: 'Junior–Senior',
    rows: [
      { id: 't11-1', gejala: 'Infinite re-render', penyebab: 'State update memicu render yang memicu state update', konsep: 'Render Lifecycle' },
      { id: 't11-2', gejala: 'Stale closure', penyebab: 'Callback menangkap state lama', konsep: 'Closure Semantics, Dependency Arrays' },
      { id: 't11-3', gejala: 'Memory leak in UI', penyebab: 'Listener/timer/subscription tidak dibersihkan', konsep: 'Cleanup Lifecycle' },
      { id: 't11-4', gejala: 'Hydration mismatch', penyebab: 'HTML server dan client tidak sama', konsep: 'SSR Hydration' },
      { id: 't11-5', gejala: 'Layout shift', penyebab: 'Konten bergeser saat resource dimuat', konsep: 'CLS, Reserved Dimensions' },
      { id: 't11-6', gejala: 'FOUC/FOUT', penyebab: 'Style/font muncul terlambat', konsep: 'Critical CSS, Font Loading' },
      { id: 't11-7', gejala: 'CORS blocked', penyebab: 'Browser menolak cross-origin response', konsep: 'CORS' },
      { id: 't11-8', gejala: 'Mixed content', penyebab: 'HTTPS page memuat HTTP resource', konsep: 'Secure Context' },
      { id: 't11-9', gejala: 'Browser API incompatibility', penyebab: 'API tidak tersedia di browser tertentu', konsep: 'Feature Detection, Polyfill' },
      { id: 't11-10', gejala: 'Event bubbling bug', penyebab: 'Event parent ikut terpanggil', konsep: 'Propagation Control' },
      { id: 't11-11', gejala: 'Event capture bug', penyebab: 'Handler berjalan pada fase yang tidak diharapkan', konsep: 'Capture/Bubble Phases' },
      { id: 't11-12', gejala: 'DOM race', penyebab: 'Script mengakses element sebelum tersedia', konsep: 'Lifecycle, DOMContentLoaded' },
      { id: 't11-13', gejala: 'Layout thrashing', penyebab: 'Read/write layout berulang memicu reflow mahal', konsep: 'Batch DOM Operations' },
      { id: 't11-14', gejala: 'Main-thread blocking', penyebab: 'JavaScript berat membekukan UI', konsep: 'Web Workers, Chunking' },
      { id: 't11-15', gejala: 'Large bundle', penyebab: 'Initial JS terlalu besar', konsep: 'Code Splitting, Tree Shaking' },
      { id: 't11-16', gejala: 'Client cache stale', penyebab: 'UI menampilkan data lama', konsep: 'Cache Invalidation' },
      { id: 't11-17', gejala: 'Optimistic UI rollback bug', penyebab: 'UI sudah berubah tetapi server gagal', konsep: 'Transactional UI State' },
      { id: 't11-18', gejala: 'Form state loss', penyebab: 'State form hilang saat navigation/refresh', konsep: 'Persistence, State Management' },
    ],
  },
  {
    id: 'tier12',
    title: 'TIER 12 — Node.js, Server Runtime & Process',
    subtitle: 'Mid–Senior',
    rows: [
      { id: 't12-1', gejala: 'Event-loop blocking', penyebab: 'CPU-heavy work menghentikan request lain', konsep: 'Worker Threads, Async I/O' },
      { id: 't12-2', gejala: 'Unhandled exception', penyebab: 'Exception lolos tanpa boundary', konsep: 'Process-level Error Handling' },
      { id: 't12-3', gejala: 'Unhandled rejection', penyebab: 'Promise rejection tidak memiliki handler', konsep: 'Async Error Boundary' },
      { id: 't12-4', gejala: 'Process crash loop', penyebab: 'Service crash lalu restart berulang', konsep: 'Crash Diagnosis, Backoff' },
      { id: 't12-5', gejala: 'File descriptor exhaustion', penyebab: 'Socket/file terlalu banyak terbuka', konsep: 'Resource Lifecycle, ulimit' },
      { id: 't12-6', gejala: 'Socket leak', penyebab: 'Connection tidak ditutup', konsep: 'Connection Pooling, Cleanup' },
      { id: 't12-7', gejala: 'Child process zombie', penyebab: 'Child process selesai tetapi tidak direap', konsep: 'Process Management' },
      { id: 't12-8', gejala: 'Environment variable missing', penyebab: 'Config runtime tidak tersedia', konsep: 'Configuration Validation' },
      { id: 't12-9', gejala: 'Signal handling bug', penyebab: 'SIGTERM/SIGINT tidak ditangani dengan benar', konsep: 'Graceful Shutdown' },
      { id: 't12-10', gejala: 'Graceful shutdown timeout', penyebab: 'Server tidak menyelesaikan request sebelum mati', konsep: 'Drain Connections' },
      { id: 't12-11', gejala: 'Unhandled stream error', penyebab: 'Readable/Writable stream error tidak ditangani', konsep: 'Stream Error Propagation' },
      { id: 't12-12', gejala: 'Backpressure ignored', penyebab: 'Stream producer membanjiri consumer', konsep: 'Stream Backpressure' },
      { id: 't12-13', gejala: 'Heap out of memory', penyebab: 'Heap mencapai limit', konsep: 'Heap Profiling, Memory Limits' },
      { id: 't12-14', gejala: 'Log flooding', penyebab: 'Error menyebabkan log volume ekstrem', konsep: 'Sampling, Rate-limited Logging' },
    ],
  },
  {
    id: 'tier13',
    title: 'TIER 13 — DevOps, Containers & Kubernetes',
    subtitle: 'Senior',
    rows: [
      { id: 't13-1', gejala: 'Works on my machine', penyebab: 'Environment developer berbeda dari production', konsep: 'Containers, IaC' },
      { id: 't13-2', gejala: 'Image drift', penyebab: 'Server menjalankan image berbeda dari yang dikira', konsep: 'Immutable Deployments' },
      { id: 't13-3', gejala: 'Container OOMKilled', penyebab: 'Container melewati memory limit', konsep: 'Resource Limits' },
      { id: 't13-4', gejala: 'CrashLoopBackOff', penyebab: 'Container terus gagal start', konsep: 'Startup Diagnostics' },
      { id: 't13-5', gejala: 'Readiness failure', penyebab: 'Pod hidup tetapi belum siap menerima traffic', konsep: 'Readiness Probe' },
      { id: 't13-6', gejala: 'Liveness failure', penyebab: 'Probe menganggap aplikasi mati sehingga direstart', konsep: 'Liveness Probe' },
      { id: 't13-7', gejala: 'Startup probe failure', penyebab: 'Aplikasi lambat start sehingga dibunuh terlalu cepat', konsep: 'Startup Probe' },
      { id: 't13-8', gejala: 'ConfigMap/Secret mismatch', penyebab: 'Runtime config tidak sesuai versi aplikasi', konsep: 'Config Versioning' },
      { id: 't13-9', gejala: 'Pod scheduling failure', penyebab: 'Tidak ada node yang memenuhi constraint', konsep: 'Scheduler, Requests/Limits' },
      { id: 't13-10', gejala: 'Image pull failure', penyebab: 'Registry/image tidak dapat diakses', konsep: 'Registry Auth, Image Tags' },
      { id: 't13-11', gejala: 'Persistent volume failure', penyebab: 'Storage tidak attach/mount', konsep: 'Storage Classes, CSI' },
      { id: 't13-12', gejala: 'DNS/service discovery failure', penyebab: 'Service name tidak resolve', konsep: 'Cluster DNS' },
      { id: 't13-13', gejala: 'Ingress misconfiguration', penyebab: 'Traffic tidak sampai ke service', konsep: 'Ingress Routing' },
      { id: 't13-14', gejala: 'Rolling deployment failure', penyebab: 'Versi baru gagal tetapi traffic sudah berpindah', konsep: 'Health Checks, Rollout Strategy' },
      { id: 't13-15', gejala: 'Resource starvation', penyebab: 'CPU/memory cluster habis', konsep: 'Capacity Planning' },
      { id: 't13-16', gejala: 'Secret leakage', penyebab: 'Credential muncul di image/log/config', konsep: 'Secret Management' },
      { id: 't13-17', gejala: 'Backup exists but restore fails', penyebab: 'Backup tidak dapat dipakai saat disaster', konsep: 'Restore Drills' },
      { id: 't13-18', gejala: 'Configuration drift', penyebab: 'Infra aktual berbeda dari deklarasi', konsep: 'Infrastructure as Code' },
    ],
  },
  {
    id: 'tier14',
    title: 'TIER 14 — Observability, Debugging & Production Failures',
    subtitle: 'Senior',
    rows: [
      { id: 't14-1', gejala: 'Error tanpa context', penyebab: 'Log hanya berisi pesan error', konsep: 'Structured Logging' },
      { id: 't14-2', gejala: 'Missing correlation ID', penyebab: 'Sulit mengikuti satu request lintas service', konsep: 'Trace/Correlation ID' },
      { id: 't14-3', gejala: 'High latency tanpa root cause', penyebab: 'Tidak diketahui komponen bottleneck', konsep: 'Distributed Tracing' },
      { id: 't14-4', gejala: 'Metric cardinality explosion', penyebab: 'Label metric terlalu banyak sehingga storage/DB terbebani', konsep: 'Cardinality Control' },
      { id: 't14-5', gejala: 'Alert fatigue', penyebab: 'Terlalu banyak alert membuat sinyal penting terabaikan', konsep: 'Alert Design, SLO' },
      { id: 't14-6', gejala: 'Silent failure', penyebab: 'Sistem gagal tetapi tidak menghasilkan alert', konsep: 'Health Checks, Synthetic Monitoring' },
      { id: 't14-7', gejala: 'Logging sensitive data', penyebab: 'PII/secret masuk log', konsep: 'Log Redaction' },
      { id: 't14-8', gejala: 'Sampling hides critical error', penyebab: 'Sampling membuang event penting', konsep: 'Tail-based Sampling' },
      { id: 't14-9', gejala: 'Clock mismatch in logs', penyebab: 'Timestamp antar service sulit disejajarkan', konsep: 'UTC, Clock Sync' },
      { id: 't14-10', gejala: 'Missing audit trail', penyebab: 'Tidak dapat diketahui siapa melakukan perubahan', konsep: 'Audit Logging' },
      { id: 't14-11', gejala: 'Bad error classification', penyebab: 'Semua failure dianggap sama', konsep: 'Error Taxonomy' },
      { id: 't14-12', gejala: 'Retry masks root cause', penyebab: 'Retry membuat masalah asli sulit terlihat', konsep: 'Retry Metrics' },
      { id: 't14-13', gejala: 'Observability blind spot', penyebab: 'Dependency penting tidak memiliki telemetry', konsep: 'Instrumentation Coverage' },
      { id: 't14-14', gejala: 'Noisy stack traces', penyebab: 'Stack trace tidak menunjuk boundary penyebab', konsep: 'Error Chaining, Causal Context' },
    ],
  },
  {
    id: 'tier15',
    title: 'TIER 15 — Testing & Software Correctness',
    subtitle: 'Mid–Senior',
    rows: [
      { id: 't15-1', gejala: 'Flaky test', penyebab: 'Test kadang pass kadang fail tanpa perubahan code', konsep: 'Deterministic Tests' },
      { id: 't15-2', gejala: 'Test pollution', penyebab: 'State test sebelumnya memengaruhi test berikutnya', konsep: 'Isolation, Setup/Teardown' },
      { id: 't15-3', gejala: 'Mock drift', penyebab: 'Mock tidak lagi mencerminkan implementasi nyata', konsep: 'Contract Testing' },
      { id: 't15-4', gejala: 'False positive test', penyebab: 'Test pass walau behavior salah', konsep: 'Assertion Quality' },
      { id: 't15-5', gejala: 'False negative test', penyebab: 'Test fail padahal behavior benar', konsep: 'Test Environment' },
      { id: 't15-6', gejala: 'Missing edge-case test', penyebab: 'Bug muncul pada boundary/empty/error path', konsep: 'Boundary Testing' },
      { id: 't15-7', gejala: 'Race-condition test gap', penyebab: 'Concurrency bug tidak tertangkap test biasa', konsep: 'Stress/Concurrency Testing' },
      { id: 't15-8', gejala: 'Integration environment mismatch', penyebab: 'Test environment berbeda dari production', konsep: 'Environment Parity' },
      { id: 't15-9', gejala: 'Snapshot explosion', penyebab: 'Snapshot terlalu banyak sehingga review tidak bermakna', konsep: 'Focused Assertions' },
      { id: 't15-10', gejala: 'Mutation testing failure', penyebab: 'Test tidak mendeteksi perubahan logika', konsep: 'Mutation Testing' },
      { id: 't15-11', gejala: 'Non-deterministic test', penyebab: 'Random/time/network membuat hasil berubah', konsep: 'Seed Control, Fake Clock' },
      { id: 't15-12', gejala: 'Test timeout', penyebab: 'Test menggantung karena async/resource leak', konsep: 'Timeouts, Cleanup' },
      { id: 't15-13', gejala: 'Regression bug', penyebab: 'Perubahan baru merusak behavior lama', konsep: 'Regression Suite' },
      { id: 't15-14', gejala: 'Property violation', penyebab: 'Output melanggar invariant meskipun example test lolos', konsep: 'Property-based Testing' },
    ],
  },
  {
    id: 'tier16',
    title: 'TIER 16 — Compiler, Build System & Toolchain',
    subtitle: 'Senior',
    rows: [
      { id: 't16-1', gejala: 'Compiler error', penyebab: 'Program tidak memenuhi aturan bahasa', konsep: 'Compiler Diagnostics' },
      { id: 't16-2', gejala: 'Type inference failure', penyebab: 'Compiler tidak dapat menentukan tipe', konsep: 'Type Annotations, Generic Constraints' },
      { id: 't16-3', gejala: 'Generic constraint failure', penyebab: 'Tipe tidak memenuhi constraint', konsep: 'Type System' },
      { id: 't16-4', gejala: 'Linker error', penyebab: 'Symbol/dependency binary tidak ditemukan', konsep: 'Linking, ABI' },
      { id: 't16-5', gejala: 'Duplicate symbol', penyebab: 'Symbol didefinisikan lebih dari sekali', konsep: 'Linkage' },
      { id: 't16-6', gejala: 'Undefined symbol', penyebab: 'Declaration ada tetapi implementation tidak ditemukan', konsep: 'Linker/Library Resolution' },
      { id: 't16-7', gejala: 'ABI incompatibility', penyebab: 'Binary berbeda layout/calling convention', konsep: 'ABI Compatibility' },
      { id: 't16-8', gejala: 'Dependency resolution conflict', penyebab: 'Versi package saling bertentangan', konsep: 'Dependency Graph' },
      { id: 't16-9', gejala: 'Lockfile drift', penyebab: 'Install menghasilkan dependency berbeda', konsep: 'Lockfiles' },
      { id: 't16-10', gejala: 'Build cache poisoning', penyebab: 'Cache build menyimpan artifact salah', konsep: 'Cache Invalidation' },
      { id: 't16-11', gejala: 'Transitive dependency vulnerability', penyebab: 'Package tidak langsung membawa dependency bermasalah', konsep: 'Dependency Audit' },
      { id: 't16-12', gejala: 'Compiler optimization bug', penyebab: 'Optimisasi mengekspos undefined behavior/asumsi salah', konsep: 'Compiler Semantics' },
      { id: 't16-13', gejala: 'Generated code drift', penyebab: 'Generated artifact tidak sinkron dengan source', konsep: 'Code Generation' },
      { id: 't16-14', gejala: 'Cross-compilation failure', penyebab: 'Target platform berbeda dari host', konsep: 'Toolchain/Target Triple' },
    ],
  },
  {
    id: 'tier17',
    title: 'TIER 17 — Networking, OS & Systems',
    subtitle: 'Senior/Expert',
    rows: [
      { id: 't17-1', gejala: 'Ephemeral port exhaustion', penyebab: 'Client kehabisan source port untuk koneksi baru', konsep: 'Connection Reuse, Port Range' },
      { id: 't17-2', gejala: 'TCP connection leak', penyebab: 'Socket tetap ESTABLISHED/CLOSE_WAIT', konsep: 'Socket Lifecycle' },
      { id: 't17-3', gejala: 'TIME_WAIT explosion', penyebab: 'Banyak koneksi pendek menumpuk', konsep: 'Keep-alive, Connection Reuse' },
      { id: 't17-4', gejala: 'MTU/fragmentation issue', penyebab: 'Packet besar gagal melewati network path', konsep: 'Path MTU Discovery' },
      { id: 't17-5', gejala: 'Packet loss', penyebab: 'Packet hilang menyebabkan retransmission/latency', konsep: 'TCP Retransmission' },
      { id: 't17-6', gejala: 'Network jitter', penyebab: 'Latency berubah-ubah', konsep: 'QoS, Buffering' },
      { id: 't17-7', gejala: 'Head-of-line blocking', penyebab: 'Satu paket/request menghambat data lain', konsep: 'HTTP/2, HTTP/3' },
      { id: 't17-8', gejala: 'DNS cache poisoning', penyebab: 'Resolver menerima data DNS berbahaya', konsep: 'DNS Security' },
      { id: 't17-9', gejala: 'File descriptor exhaustion', penyebab: 'Process kehabisan descriptor', konsep: 'Resource Limits' },
      { id: 't17-10', gejala: 'Process limit exhaustion', penyebab: 'Tidak dapat membuat thread/process baru', konsep: 'ulimit, Process Limits' },
      { id: 't17-11', gejala: 'Disk full', penyebab: 'Write gagal dan service dapat crash', konsep: 'Disk Monitoring' },
      { id: 't17-12', gejala: 'Inode exhaustion', penyebab: 'Filesystem tidak dapat membuat file meskipun space masih ada', konsep: 'Inode Monitoring' },
      { id: 't17-13', gejala: 'Filesystem corruption', penyebab: 'Metadata/data disk rusak', konsep: 'Filesystem Checks, Journaling' },
      { id: 't17-14', gejala: 'Kernel OOM', penyebab: 'OS membunuh process karena memory pressure', konsep: 'Memory Pressure Analysis' },
      { id: 't17-15', gejala: 'Resource starvation', penyebab: 'CPU, memory, I/O, atau FD habis', konsep: 'Resource Accounting' },
    ],
  },
  {
    id: 'tier18',
    title: 'TIER 18 — Language Semantics, Type Systems & Formal Correctness',
    subtitle: 'Expert',
    rows: [
      { id: 't18-1', gejala: 'Type unsoundness', penyebab: 'Program lolos type checker tetapi dapat menghasilkan state invalid', konsep: 'Type Soundness' },
      { id: 't18-2', gejala: 'Variance error', penyebab: 'Subtype relation generic tidak aman', konsep: 'Covariance/Contravariance' },
      { id: 't18-3', gejala: 'Lifetime violation', penyebab: 'Reference hidup lebih lama/pendek dari object', konsep: 'Borrow Checking, Ownership' },
      { id: 't18-4', gejala: 'Data race in type-safe code', penyebab: 'Parallel mutation melanggar synchronization contract', konsep: 'Send/Sync or Ownership Models' },
      { id: 't18-5', gejala: 'Algebraic data type exhaustiveness failure', penyebab: 'Case baru tidak ditangani', konsep: 'Exhaustive Matching' },
      { id: 't18-6', gejala: 'Impossible state represented', penyebab: 'Model data mengizinkan kombinasi state invalid', konsep: 'Type-driven Design' },
      { id: 't18-7', gejala: 'Invariant violation', penyebab: 'Program state keluar dari kondisi yang selalu harus benar', konsep: 'Design by Contract' },
      { id: 't18-8', gejala: 'Non-total function', penyebab: 'Fungsi tidak memiliki definisi untuk seluruh domain input', konsep: 'Totality' },
      { id: 't18-9', gejala: 'Termination failure', penyebab: 'Algoritma tidak menjamin berhenti', konsep: 'Termination Proof' },
      { id: 't18-10', gejala: 'Precision loss in abstract model', penyebab: 'Representasi domain terlalu kasar untuk keputusan', konsep: 'Domain Modeling' },
      { id: 't18-11', gejala: 'Concurrency memory-order bug', penyebab: 'Atomic operation memakai ordering yang terlalu lemah', konsep: 'Memory Model' },
      { id: 't18-12', gejala: 'Undefined evaluation order', penyebab: 'Urutan evaluasi expression tidak dijamin', konsep: 'Language Specification' },
    ],
  },
  {
    id: 'tier19',
    title: 'TIER 19 — Distributed Data, Consensus & Fault Tolerance',
    subtitle: 'Expert',
    rows: [
      { id: 't19-1', gejala: 'Consensus failure', penyebab: 'Node gagal mencapai keputusan bersama', konsep: 'Raft/Paxos Concepts' },
      { id: 't19-2', gejala: 'Quorum misconfiguration', penyebab: 'Jumlah node minimum untuk keputusan salah', konsep: 'Quorum Mathematics' },
      { id: 't19-3', gejala: 'Leader lease expiry', penyebab: 'Node masih mengira dirinya leader setelah lease habis', konsep: 'Fencing Tokens' },
      { id: 't19-4', gejala: 'Split-brain write', penyebab: 'Dua leader menerima write', konsep: 'Fencing, Consensus' },
      { id: 't19-5', gejala: 'Replica divergence', penyebab: 'Replica memiliki state berbeda', konsep: 'Replication Protocol' },
      { id: 't19-6', gejala: 'Log divergence', penyebab: 'Node memiliki prefix/entry log berbeda', konsep: 'Consensus Log Matching' },
      { id: 't19-7', gejala: 'State machine inconsistency', penyebab: 'Node menerapkan event berbeda', konsep: 'Deterministic State Machine' },
      { id: 't19-8', gejala: 'Checkpoint corruption', penyebab: 'Snapshot tidak merepresentasikan state valid', konsep: 'Snapshot Verification' },
      { id: 't19-9', gejala: 'Replay bug', penyebab: 'Event replay menghasilkan state berbeda', konsep: 'Deterministic Handlers' },
      { id: 't19-10', gejala: 'Event schema incompatibility', penyebab: 'Consumer lama tidak dapat membaca event baru', konsep: 'Schema Evolution' },
      { id: 't19-11', gejala: 'Exactly-once processing assumption', penyebab: 'Crash di antara side effect dan ack menghasilkan duplikasi', konsep: 'Idempotency' },
      { id: 't19-12', gejala: 'Byzantine behavior', penyebab: 'Node dapat berperilaku arbitrer/berbahaya', konsep: 'Byzantine Fault Tolerance' },
      { id: 't19-13', gejala: 'Fencing failure', penyebab: 'Node lama masih dapat menulis setelah kehilangan leadership', konsep: 'Fencing Token' },
    ],
  },
  {
    id: 'tier20',
    title: 'TIER 20 — Performance, Capacity & Extreme Scale',
    subtitle: 'Senior/Expert',
    rows: [
      { id: 't20-1', gejala: 'CPU saturation', penyebab: 'CPU menjadi bottleneck utama', konsep: 'Profiling, Horizontal Scaling' },
      { id: 't20-2', gejala: 'Memory pressure', penyebab: 'GC/allocator bekerja ekstrem atau OOM', konsep: 'Heap Profiling' },
      { id: 't20-3', gejala: 'GC pause', penyebab: 'Garbage collector menghentikan/menurunkan throughput aplikasi', konsep: 'GC Tuning' },
      { id: 't20-4', gejala: 'Allocation storm', penyebab: 'Terlalu banyak object allocation', konsep: 'Allocation Profiling' },
      { id: 't20-5', gejala: 'I/O bottleneck', penyebab: 'Disk/network menjadi batas throughput', konsep: 'I/O Profiling' },
      { id: 't20-6', gejala: 'Lock contention', penyebab: 'Thread menghabiskan waktu menunggu lock', konsep: 'Lock Profiling' },
      { id: 't20-7', gejala: 'False sharing', penyebab: 'Core berebut cache line yang sama', konsep: 'CPU Cache, Data Layout' },
      { id: 't20-8', gejala: 'Cache locality failure', penyebab: 'Access pattern buruk terhadap CPU cache', konsep: 'Data-oriented Design' },
      { id: 't20-9', gejala: 'Queueing collapse', penyebab: 'Latency melonjak ketika utilization mendekati kapasitas', konsep: 'Queueing Theory' },
      { id: 't20-10', gejala: 'Load shedding failure', penyebab: 'Sistem menerima traffic lebih besar daripada kemampuan', konsep: 'Admission Control' },
      { id: 't20-11', gejala: 'Autoscaling lag', penyebab: 'Scaling terlambat terhadap traffic spike', konsep: 'Predictive/Reactive Scaling' },
      { id: 't20-12', gejala: 'Capacity planning error', penyebab: 'Resource dihitung tanpa growth/failure headroom', konsep: 'Capacity Models' },
      { id: 't20-13', gejala: 'Hot partition', penyebab: 'Satu shard menerima traffic tidak seimbang', konsep: 'Partition Key Design' },
      { id: 't20-14', gejala: 'Cardinality explosion', penyebab: 'Jumlah key/series/partition meningkat ekstrem', konsep: 'Cardinality Management' },
      { id: 't20-15', gejala: 'N+1 at scale', penyebab: 'Pattern kecil menjadi catastrophic pada jutaan record', konsep: 'Batching, Set-based Operations' },
      { id: 't20-16', gejala: 'Algorithmic complexity trap', penyebab: 'Input sedikit lebih besar membuat runtime meledak', konsep: 'Big-O, Amortized Analysis' },
    ],
  },
  {
    id: 'tier21',
    title: 'TIER 21 — Data Engineering & ML Failure Modes',
    subtitle: 'Mid–Expert',
    rows: [
      { id: 't21-1', gejala: 'Data drift', penyebab: 'Distribusi input berubah dari waktu training', konsep: 'Drift Monitoring' },
      { id: 't21-2', gejala: 'Concept drift', penyebab: 'Hubungan input-output berubah', konsep: 'Model Monitoring' },
      { id: 't21-3', gejala: 'Training-serving skew', penyebab: 'Transformasi training berbeda dengan production', konsep: 'Feature Pipelines' },
      { id: 't21-4', gejala: 'Data leakage', penyebab: 'Informasi masa depan masuk ke training', konsep: 'Temporal Validation' },
      { id: 't21-5', gejala: 'Label leakage', penyebab: 'Label/target bocor ke feature', konsep: 'Feature Review' },
      { id: 't21-6', gejala: 'Class imbalance', penyebab: 'Model mengabaikan kelas minoritas', konsep: 'Sampling, Class Weights' },
      { id: 't21-7', gejala: 'Feature missingness', penyebab: 'Feature production hilang/berubah', konsep: 'Data Contracts' },
      { id: 't21-8', gejala: 'Pipeline partial failure', penyebab: 'Sebagian batch sukses dan sebagian gagal', konsep: 'Checkpointing, Exactly-once Semantics' },
      { id: 't21-9', gejala: 'Duplicate records', penyebab: 'Pipeline mengulang batch', konsep: 'Deduplication, Idempotency' },
      { id: 't21-10', gejala: 'Late-arriving data', penyebab: 'Data datang setelah window diproses', konsep: 'Watermarks' },
      { id: 't21-11', gejala: 'Out-of-order events', penyebab: 'Event timestamp order berbeda dari arrival order', konsep: 'Event-time Processing' },
      { id: 't21-12', gejala: 'Schema evolution failure', penyebab: 'Producer mengubah field tanpa consumer compatibility', konsep: 'Schema Registry' },
      { id: 't21-13', gejala: 'Model serving timeout', penyebab: 'Inference lebih lambat dari SLA', konsep: 'Model Optimization' },
      { id: 't21-14', gejala: 'Model degradation', penyebab: 'Akurasi turun setelah deployment', konsep: 'Monitoring, Retraining' },
      { id: 't21-15', gejala: 'Non-reproducible experiment', penyebab: 'Data/code/seed/environment tidak dikunci', konsep: 'Experiment Tracking' },
    ],
  },
  {
    id: 'tier22',
    title: 'TIER 22 — Hardware, Embedded & Real-Time',
    subtitle: 'Expert',
    rows: [
      { id: 't22-1', gejala: 'Watchdog reset', penyebab: 'Firmware hang sehingga watchdog me-reset device', konsep: 'Watchdog Design' },
      { id: 't22-2', gejala: 'Stack overflow on MCU', penyebab: 'Stack kecil habis karena recursion/local allocation', konsep: 'Stack Analysis' },
      { id: 't22-3', gejala: 'Heap fragmentation', penyebab: 'Free memory ada tetapi tidak cukup contiguous', konsep: 'Static Allocation' },
      { id: 't22-4', gejala: 'Interrupt race', penyebab: 'ISR dan main loop mengakses state yang sama', konsep: 'Atomicity, Critical Sections' },
      { id: 't22-5', gejala: 'Priority inversion', penyebab: 'Task prioritas tinggi menunggu task rendah', konsep: 'Priority Inheritance' },
      { id: 't22-6', gejala: 'Missed deadline', penyebab: 'Task real-time selesai setelah deadline', konsep: 'Worst-case Execution Time' },
      { id: 't22-7', gejala: 'Jitter violation', penyebab: 'Timing sensor/control tidak stabil', konsep: 'Deterministic Scheduling' },
      { id: 't22-8', gejala: 'Brownout reset', penyebab: 'Voltage turun sehingga MCU reset', konsep: 'Power Integrity' },
      { id: 't22-9', gejala: 'Peripheral register race', penyebab: 'Register berubah oleh hardware/ISR saat dibaca', konsep: 'Atomic Register Access' },
      { id: 't22-10', gejala: 'DMA coherency bug', penyebab: 'CPU dan DMA melihat cache/memory state berbeda', konsep: 'Cache Coherency' },
      { id: 't22-11', gejala: 'Endianness bug', penyebab: 'Byte order berbeda antar platform', konsep: 'Serialization, Byte Order' },
      { id: 't22-12', gejala: 'Memory-mapped I/O misuse', penyebab: 'Register hardware diakses seperti memory biasa tanpa aturan', konsep: 'Volatile, Hardware Semantics' },
      { id: 't22-13', gejala: 'Firmware update bricked device', penyebab: 'Update gagal dan device tidak dapat boot', konsep: 'A/B Partition, Recovery Boot' },
    ],
  },
  {
    id: 'tier23',
    title: 'TIER 23 — Architecture & Socio-Technical Failure',
    subtitle: 'Staff/Architect',
    rows: [
      { id: 't23-1', gejala: 'Architecture erosion', penyebab: 'Implementasi perlahan menyimpang dari arsitektur', konsep: 'Architecture Fitness Functions' },
      { id: 't23-2', gejala: 'Dependency cycle across domains', penyebab: 'Boundary antar domain runtuh', konsep: 'Bounded Contexts' },
      { id: 't23-3', gejala: 'Distributed monolith', penyebab: 'Service terpisah tetapi tetap deploy/coordinate bersama', konsep: 'Independent Deployability' },
      { id: 't23-4', gejala: 'Shared database coupling', penyebab: 'Service berbeda bergantung schema DB yang sama', konsep: 'Data Ownership' },
      { id: 't23-5', gejala: 'Organizational coupling', penyebab: 'Arsitektur mengikuti struktur tim secara buruk', konsep: 'Conway\'s Law' },
      { id: 't23-6', gejala: 'Change amplification', penyebab: 'Perubahan kecil menyebar ke banyak komponen', konsep: 'Modularity' },
      { id: 't23-7', gejala: 'Operational complexity explosion', penyebab: 'Distribusi menambah failure mode lebih cepat dari manfaat', konsep: 'Complexity Budget' },
      { id: 't23-8', gejala: 'Missing failure ownership', penyebab: 'Tidak jelas siapa bertanggung jawab saat incident', konsep: 'Operational Ownership' },
      { id: 't23-9', gejala: 'Runbook gap', penyebab: 'Tim tidak tahu prosedur recovery', konsep: 'Runbooks' },
      { id: 't23-10', gejala: 'Alert ownership gap', penyebab: 'Alert ada tetapi tidak memiliki owner', konsep: 'On-call Design' },
      { id: 't23-11', gejala: 'Unsafe migration', penyebab: 'Perubahan data/schema tidak memiliki rollback path', konsep: 'Expand/Contract' },
      { id: 't23-12', gejala: 'Feature flag debt', penyebab: 'Flag lama menambah kompleksitas permanen', konsep: 'Flag Lifecycle' },
      { id: 't23-13', gejala: 'Observability debt', penyebab: 'Sistem tumbuh lebih cepat daripada telemetry', konsep: 'Observability Design' },
      { id: 't23-14', gejala: 'Technical debt compounding', penyebab: 'Shortcut lama meningkatkan cost perubahan berikutnya', konsep: 'Debt Management' },
    ],
  },
  {
    id: 'tier24',
    title: 'TIER 24 — Catastrophic & Rare Failure Patterns',
    subtitle: 'Expert',
    rows: [
      { id: 't24-1', gejala: 'Cascading outage', penyebab: 'Failure lokal memicu kegagalan berantai', konsep: 'Bulkheads, Circuit Breakers' },
      { id: 't24-2', gejala: 'Correlated failure', penyebab: 'Komponen cadangan gagal karena penyebab yang sama', konsep: 'Failure Domain Diversity' },
      { id: 't24-3', gejala: 'Common-mode failure', penyebab: 'Redundansi tidak berguna karena dependency bersama', konsep: 'Fault Isolation' },
      { id: 't24-4', gejala: 'Retry storm during outage', penyebab: 'Client memperburuk service yang sudah gagal', konsep: 'Retry Budgets, Jitter' },
      { id: 't24-5', gejala: 'Thundering herd after recovery', penyebab: 'Traffic melonjak saat dependency pulih', konsep: 'Warm-up, Rate Limiting' },
      { id: 't24-6', gejala: 'Cache stampede at global scale', penyebab: 'Expiration serentak menghasilkan load ekstrem', konsep: 'Jitter, Request Coalescing' },
      { id: 't24-7', gejala: 'Clock rollback bug', penyebab: 'Waktu sistem mundur dan merusak ordering/expiry', konsep: 'Monotonic Clock' },
      { id: 't24-8', gejala: 'Leap second/time anomaly', penyebab: 'Asumsi waktu monoton gagal', konsep: 'Time Semantics' },
      { id: 't24-9', gejala: 'Leap year/date boundary bug', penyebab: 'Tanggal kalender menghasilkan hasil salah', konsep: 'Calendar-aware APIs' },
      { id: 't24-10', gejala: 'Data corruption with valid checksum', penyebab: 'Integrity check tidak mencakup semantic corruption', konsep: 'Semantic Validation' },
      { id: 't24-11', gejala: 'Silent data loss', penyebab: 'Data hilang tanpa exception', konsep: 'Durability, Reconciliation' },
      { id: 't24-12', gejala: 'Disaster recovery RPO violation', penyebab: 'Data yang hilang melebihi target recovery point', konsep: 'Replication/Backup Strategy' },
      { id: 't24-13', gejala: 'Disaster recovery RTO violation', penyebab: 'Recovery lebih lama dari target', konsep: 'Recovery Automation' },
      { id: 't24-14', gejala: 'Regional outage', penyebab: 'Region/cloud zone gagal total', konsep: 'Multi-region Architecture' },
      { id: 't24-15', gejala: 'Dependency supply-chain compromise', penyebab: 'Dependency terpercaya berubah menjadi sumber serangan', konsep: 'SBOM, Signing, Provenance' },
    ],
  },
];

export const CATALOG_LEARNING_GUIDE = [
  'Prioritas utama adalah error yang pernah kamu temui: cari gejalanya, identifikasi nama failure mode, lalu pahami mekanismenya.',
  'Jangan menganggap error hanya exception. Race condition, data corruption, latency collapse, security flaw, memory bug, deployment failure, dan distributed-system failure juga merupakan failure mode.',
  'Untuk setiap kasus, latihan diagnosis harus mengikuti: reproduce -> isolate -> observe -> hypothesize -> test hypothesis -> fix -> regression test.',
  'Semakin tinggi tier, semakin sering bug tidak menghasilkan error message yang jelas. Fokus berpindah dari membaca exception ke membaca system behavior.',
  'Target penguasaan bukan hafal semua istilah, tetapi mampu memetakan gejala produksi ke kelas failure yang tepat.',
  'Untuk error yang language-specific, tambahkan katalog turunan berdasarkan bahasa: JavaScript/TypeScript, Python, Java, C#, Go, Rust, C/C++, SQL, dan shell.',
];
